- hosts: all
#  become: true

  vars:
   age: 1d
   paths: /var/log/nginx

  tasks:
    - name: find all files that are older than {{ age }}
      find:
        path: '{{ paths }}'
        age: '{{ age }}'
        recurse: yes
#        patterns: '*.log'
      register: FilesToClean

    - name: print files to be removed
      debug:
        var: FilesToClean

    - name: remove registered files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ FilesToClean.files }}"


